## Configure the server to accept both mutual TLS and plain text traffic
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: example-espresso-shop-permissive
spec:
  targets:
  - name: espresso-shop-product-catalog-svc
  peers:
  - mtls:
      mode: PERMISSIVE
      # mode: STRICT
---
### Configure clients to send mutual TLS traffic
apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: espresso-shop-product-catalog
spec:
  host: espresso-shop-product-catalog-svc
  subsets:
  - name: v1
    labels:
      version: v1
  # trafficPolicy:
  #   tls:
  #     mode: ISTIO_MUTUAL


## istioctl authn tls-check espresso-shop-product-catalog-svc.default.svc.cluster.local